### PR TITLE
Add json schemas for classifier, evaluation modules

### PR DESCRIPTION
**Pull request by pcallier**
These schemas should be considered drafts and up for discussion.

### CODE REVIEW

**Comment by dave-lab41** [comment]
I think we need cluster_id in cluster_schema.json

**Comment by bethke** [comment]
So with the evaluation output file, it looks like we then will have a file (or something) which explains what the run entailed?  An alternative method could include the various run components in the json itself, so things like dataset, normalizer, model, model parameters, etc.  We did something like this for Hermes which worked well, but we might have had less modules than this project will have.  Thoughts?

**Comment by pcallier** [comment]
so, sacred will be in the mix here somewhere as well and it supposedly takes care of many such things. not sure if that means we don't also follow what you're talking about and add more metadata to the evaluation output as well, but maybe we should tackle adding sacred to the mix to see how it works before deciding

**Comment by dave-lab41** [comment]
Is the idea that sacred would map the run_id from the evaluation output file back to the dataset, normalizer, model, model parameters, etc. ? If so, I assume that sacred creates the run_id for us.

**Comment by pcallier** [comment]
Yes (as long as you tell it to store those fields) and yes. It would be a matter of seeing how easy it is to deal with Sacred's outputs or if we want to short-circuit it for storing the key metrics from the latest run, or something of that nature.

**Pull request merged**
